# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
solc = "0.8.30"
cache = true
cache_path = 'cache'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
verbosity = 3
remappings = [
    "@src/=src/",
    "@test/=test/",
    "@openzeppelin/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin-upgrades/=node_modules/@openzeppelin/contracts-upgradeable/contracts/",
    "forge-std/=node_modules/forge-std/src/"
]

# TODO: remove this
via_ir = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
multiline_func_header = 'params_first'

